### ISSUE TITLE
Handle the `ExhaustsResources` issue

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#105]
When doing a too big batch, we may get the error [`ExhaustsResources`](https://paritytech.github.io/polkadot-sdk/master/sp_runtime/transaction_validity/enum.InvalidTransaction.html#variant.ExhaustsResources)
> The transaction would exhaust the resources of current block.
The transaction might be valid, but there are not enough resources left in the current block.

I came acros this when
- undelegating 10+ tracks
- remove vote
- delegating 10+ tracks

So I imagine this may happen on Polkadot or Kusama. We need to check.

To prevent this, we need to split in different Txs, I don't think there's another way... Pinging the papi team here: https://github.com/polkadot-api/polkadot-api/issues/695

edit: follow the link, there's an answer and some code even :heart:

**Comment by wirednkod** [comment]
I came to this issue, as well when I tried to make a simple delegation on Westend
