### ISSUE TITLE
Add Network in localstorage

### ISSUE THREAD

**Issue by wirednkod** [delegit-xyz/dashboard#110]
The idea is to have the network saved in the localstorage, so that a returning visitor (or even a refresh), will not default/land to Polkadot network as it is happening now

**Comment by Tbaut** [comment]
I wouldn't put this as a bug, and I'd say this suffices
https://github.com/delegit-xyz/dashboard/issues/27

**Comment by wirednkod** [comment]
It is not a bug. Its an enhancement. When a user lands in delegit.xyz - there is no Network query in the string.
The query in the string should automatically update the local storage as well

**Comment by Tbaut** [comment]
Ah I meant regarding the prio, P0 is for bugs in prod basically. It's in the description
> Added to issues and PRs relating to a critical severity bugs.
