### ISSUE TITLE
Toaster UI for complete actions: Delegate, Undelegate, Unlock funds

### ISSUE THREAD

**Issue by goldsteinsveta** [delegit-xyz/dashboard#133]
<img width="1245" alt="Screenshot 2024-09-13 at 20 14 09" src="https://github.com/user-attachments/assets/846ad488-b1bd-460f-a3b4-09dea365b2c6">

**Comment by Tbaut** [comment]
what's the story, do you wish you had toasters to see this? But it's not as granular. We now have toasters for tx, and the txs do a million things, all at once in general. Undelegating, unvoting, delegating etc.. I fear this wouldn't fit well in a toaster :see_no_evil:

**Comment by goldsteinsveta** [comment]
Closed in #112 I didn't pull properly
