### ISSUE TITLE
No clear error when closing the Talisman popup

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#147]
start a Tx, then just close the popup. The console error is "Error: Canceled" but it sounds like nothing gets propagated for users.
![image](https://github.com/user-attachments/assets/a110e17c-0dd8-4204-a5a0-a3f3f4eca14a)

![image](https://github.com/user-attachments/assets/45c832cb-b679-474f-85a1-1feaa7d689d9)

**Comment by uDaiko** [comment]
I'll have a look. Could you assign me to this issue?

**Comment by Tbaut** [comment]
go for it, thanks
