### ISSUE TITLE
Deploy to delegit.xyz

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#26]
With the right CI workflow so that it's deployed on merge to `main`

**Comment by wirednkod** [comment]
CI workflow is almost ready to deploy gh-pages as seen here: https://github.com/delegit-xyz/dashboard/issues/43
Should this change and deploy to delegit.xyz?
I think it is better to have the gh-page for pre-release-test version, and create a `deploy` branch that once merged will deploy to delegit.xyz. WDYT?

**Comment by Tbaut** [comment]
I'd say we can skip the pre-release, and just have continuous delivery, whatever is on `main` is what's live. This is what I have on Multix, and this means being somewhat careful about what we merge in general, reviewing and testing things well.

If the gh page works, and https://github.com/delegit-xyz/dashboard/issues/43 is done, then I can just point the DNS from delegit.xyz to the gh page domain.

**Comment by Tbaut** [comment]
Not sure if GH provides server side stats, if it doesn't I can also use Cloudflare, again that's what I have on Multix, working well: https://github.com/ChainSafe/Multix/blob/main/.github/workflows/deploy-ui-cf-pages.yaml

**Comment by wirednkod** [comment]
> Not sure if GH provides server side stats, if it doesn't I can also use Cloudflare, again that's what I have on Multix, working well: [ChainSafe/Multix@`main`/.github/workflows/deploy-ui-cf-pages.yaml](https://github.com/ChainSafe/Multix/blob/main/.github/workflows/deploy-ui-cf-pages.yaml?rgh-link-date=2024-08-25T10%3A56%3A22Z)

AFAIK it does not - so I think using Cloudflare makes more sense

**Comment by Tbaut** [comment]
Cool creating a cloudflare page setup rn

**Comment by Tbaut** [comment]
done in https://github.com/delegit-xyz/dashboard/pull/45
