### ISSUE TITLE
Better error handling for delegation amount

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#60]
The error is displayed before any action has been taken.
Instead, the error shouldn't be displayed unless an amount has been typed in, and eventually removed

![image](https://github.com/user-attachments/assets/9bee705a-9854-4004-bebd-68e7dd257c09)

Also, better than a big banner, we should mark the input as with error, displayed in red, and have the input related text be displayed in red below, as we're used to on other websites. e.g something like this
![image](https://github.com/user-attachments/assets/344af8f6-ff76-4dc4-81e6-399fe679ff57)

**Comment by wirednkod** [comment]
The Alert component (Big box) is used here for the things that SHOULD be done as actions (Connect account - api is not connected).
For other errors we can use the red-font text as you describe
