### ISSUE TITLE
Account switching/logout does not update the information

### ISSUE THREAD

**Issue by wirednkod** [delegit-xyz/dashboard#66]
When a user is logged in (and e.g. locks appear), when switching accounts (and the 2nd account has no locks) or when logging out, the locks remain on screen

**Comment by Tbaut** [comment]
Ah thanks, I can fix this directly in the PR

**Comment by Tbaut** [comment]
ok, you merged already and I didn't realize, I think it's better for such bugs to be fixed right away if possible
