### ISSUE TITLE
Make the components import better 

### ISSUE THREAD

**Issue by wirednkod** [delegit-xyz/dashboard#67]
create an index file that will exporting all compoents so that instead of:
```ts
import { component1 } from `./ui/components/component1`;
import { component2 } from `./ui/components/component2`;
```
we should be able to :
```ts
import { component1, component2 } from `./ui/components`;
```

**Comment by Tbaut** [comment]
Up to you, I find this annoying to have to not forget to add it to an `index.ts` every time :shrug:

**Comment by wirednkod** [comment]
True - but reduces a LOT of lines of code

**Comment by Tbaut** [comment]
I really have no strong opinion there. If you prefer it that way, please go ahead, I'll make follow.
