### ISSUE TITLE
Use `ContentReveal` for delegates' large description

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#70]
It's maybe me, but I think having a modal for the large description for delegates is not intuitive.
I'd suggest to have the same design as the locks with a `ContentReveal` component.

WDYT?

**Comment by wirednkod** [comment]
Completely agree. That was during the Hackathon that we were hasty.
Will definetely check the ContentReveal and fix it.

**Comment by wirednkod** [comment]
In addition a small redesign on the Delegate Cards will take place: 
- Remove the 3 dots button and replace it with a delegate button.
- add the Content Reveal button
- add the address (+copy) in the main card (instead of the popup)
