### ISSUE TITLE
Connect to Ppl chain to get the identity of delegates

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#71]
Identity of delegates may give us some information to show to users such as twitter, website, email etc.
We should connect to the ppl chain, get the identity and somehow display these info, maybe only in "expanded mode" when the large description is shown.

BTW the ppl chain WS endpoints should be added in the `network.json`, and we should either export a `pplApi` from the `NetworkContext`, or even created an `IdentityContext` that only connects to the ppl chain and gets all the info.

**Comment by wirednkod** [comment]
Easy peasy - I'll take that task. Have done it in the Fellowship dashboard - would be a piece of cake

**Comment by wirednkod** [comment]
Completed with #124
