### ISSUE TITLE
Fix polkadot-ui unmet peer `polkadot-api` warning

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#76]
All I can see for now on Brave, when nothing appears are warnings linked to polkadot-ui. It may not be the main issue, but it'd be good to check
![image](https://github.com/user-attachments/assets/c5576c63-2bd6-45e3-890a-56049081a1e2)

Maybe checking with the dependancies as well, I get this when doing `pnpm install`
```
 WARN  Issues with peer dependencies found
.
└─┬ @polkadot-ui/react 0.0.1-alpha.15
  └── ✕ unmet peer polkadot-api@^0.12.0: found 1.0.1

Done in 3.1s

dependencies:
- @radix-ui/react-slider 1.2.0

 WARN  Issues with peer dependencies found
.
└─┬ @polkadot-ui/react 0.0.1-alpha.15
  └── ✕ unmet peer polkadot-api@^0.12.0: found 1.0.1

```

**Comment by wirednkod** [comment]
This is fixed in PR #109
