### ISSUE TITLE
Make delegate page more appealing

### ISSUE THREAD

**Issue by Tbaut** [delegit-xyz/dashboard#99]
If we want users to link to the delegate page directly, we need to make it nicers:
- show the name of the delegate with picture
- show the description, maybe just the short one, with a `ContentReveal` again?

otherwise landing on this isn't really appealing
![image](https://github.com/user-attachments/assets/239d0eb5-f413-49a6-a12d-1f779c380001)

**Comment by wirednkod** [comment]
@goldsteinsveta I assume you work on a design for this?
Keep in mind that more info can be placed here coming from the People chain. I am preparing the connection here: #124
